# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from lacp_client import Sniffer
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(980, 390, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 961, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 410, 1051, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Time_label = QtWidgets.QLabel(self.groupBox)
        self.Time_label.setGeometry(QtCore.QRect(60, 20, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Time_label.setFont(font)
        self.Time_label.setObjectName("Time_label")
        self.Time_edit = QtWidgets.QLineEdit(self.groupBox)
        self.Time_edit.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.Time_edit.setObjectName("Time_edit")
        self.sec_inf = QtWidgets.QLabel(self.groupBox)
        self.sec_inf.setGeometry(QtCore.QRect(160, 50, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sec_inf.setFont(font)
        self.sec_inf.setTextFormat(QtCore.Qt.RichText)
        self.sec_inf.setObjectName("sec_inf")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 90, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.file_info = QtWidgets.QPushButton(self.groupBox)
        self.file_info.setGeometry(QtCore.QRect(200, 90, 111, 23))
        self.file_info.setObjectName("file_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.pushButton_3.clicked.connect(self.on_click)  # соединение сигнала и слота (сигнал clicked и слот on_click)
        self.pushButton.clicked.connect(self.on_click_clear)
        self.file_info.clicked.connect(self.on_click_file)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Отчистить"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "dst"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "src"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "subtype"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "data"))
        self.Time_label.setText(_translate("MainWindow", "Time"))
        self.sec_inf.setText(_translate("MainWindow", "сек"))
        self.pushButton_3.setText(_translate("MainWindow", "Искать"))
        self.file_info.setText(_translate("MainWindow", "Читать из файла "))
    def on_click_clear(self):
        self.tableWidget.setRowCount(0)

    def on_click_file(self):
        rowPosition = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        df2 = pd.read_csv('input.txt')
        N=len(df2)
        for i in range(N):
            dst = df2.values[i][1]
            src = df2.values[i][2]
            subtype = df2.values[i][3]
            type = df2.values[i][4]
            data = df2.values[i][5]

        print(dst, src, subtype, type, data)
        self.tableWidget.setItem(rowPosition, 0, QtWidgets.QTableWidgetItem(dst))
        self.tableWidget.setItem(rowPosition, 1, QtWidgets.QTableWidgetItem(src))
        self.tableWidget.setItem(rowPosition, 2, QtWidgets.QTableWidgetItem(type))
        self.tableWidget.setItem(rowPosition, 3, QtWidgets.QTableWidgetItem("LACP"))
        self.tableWidget.setItem(rowPosition, 4, QtWidgets.QTableWidgetItem(str(data)))

    def on_click(self):
        flag=True
        time_sec=int(self.Time_edit.text())
        timing = time.time()
        sniff_tmp=Sniffer()
        sniff_tmp.sniff(time_sec)

        while True and flag:
            if time.time() - timing > time_sec:
                timing = time.time()
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("Внимание")
                msg.setText("Прошло время поиска")
                msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
                msg.exec_()
                flag=False




def GUI():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())

